spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application: 
    name: microservicecloud-congfig-atguigu-dev
---
spring:
  profiles: test
  application: 
    name: microservicecloud-congfig-atguigu-test    
